#XGTZonesGUI

Type: 1
# Type:
 # 1 = This type has 4 slots that you can select
 # 2 = This type has 7 slots that you can select

# Name:
# Here you put a custom name for an item
# (optional)Use for Color = §
Name-Chest: "Crates"
Name-Melon: "Farm"
Name-GoldenApple: "Spawn"
Name-Sword: "PVP"
Name-Egg: "Food Shop"
Name-Stone: "Mine"
Name-Sand: "Shop"
Name-Locked: "§cLOCKED"

# Message:
# Here you put a personalized message when someone clicks on that item
# (optional)Use for Color = §
# NEXT UPDATE!
Message-Chest: "Teleport to Crate Zone!"
Message-Melon: "Teleport to Farm Zone!"
Message-GoldenApple: "Teleport to Spawn Zone!"
Message-Sword: "Teleport to PVP Zone!"
Message-Egg: "Teleport to Food shop Zone!"
Message-Stone: "Teleport to Mine Zone!"
Message-Sand: "Teleport to Shop Zone!"

# Coordinates:
# Here you put the coordinates where Jews teleport you when you click on an item
#Golden Apple
GAplle-X: 104
GAplle-Y: 80
GAplle-Z: 40

#Chest
Chest-X: 104
Chest-Y: 80
Chest-Z: 40

#Melon
Melon-X: 90
Melon-Y: 80
Melon-Z: 40

#Sowrd
DMDSword-X: 104
DMDSword-Y: 80
DMDSword-Z: 40

#Egg
EGG-X: 104
EGG-Y: 80
EGG-Z: 40

#Stone
Stone-X: 104
Stone-Y: 80
Stone-Z: 40

#Sand
Sand-X: 104
Sand-Y: 80
Sand-Z: 40